#pragma once

#include <cstdint>
#include <vector>

namespace rtpt
{

// ReSTIRPTPairingTexture
// Section 3.1: a self-inverting ("involutive") pairing texture.
// The texture stores, per texel, the coordinate delta to that texel's partner. Its defining property is that following the delta twice returns to the start: if A links to B then B links to A.
// That reciprocity is the entire point. Spatial reuse needs a shift in BOTH directions for every neighbour pair - the neighbour's path into this pixel for the sample, and this pixel's path into the neighbour for the MIS weight - so when pairing is reciprocal, one shift per pixel serves both pixels and the second shift becomes free.
// Deltas are generated by random walk rather than by solving for a distribution directly: the paper reports optimization-based constructions as slow and unreliable, whereas repeated local shuffles land on a Gaussian by the central limit theorem, exactly and cheaply.

struct ReSTIRPTPairingTexture
{
  // Square edge length in texels. Deliberately not a power of two and different per neighbour slot, so the tilings of several textures never line up and produce visible structure.
  uint32_t size = 0;

  // Two signed deltas per texel (x then y), row-major, tiled over the screen.
  // int8 matches the paper's [-127, 127] encoding; a delta that large is already far outside the Gaussian's useful range.
  std::vector<int8_t> deltas;

  // True when every texel's partner links back to it.
  // Generation cannot fail silently: a broken involution would quietly double-count MIS weights rather than crash, so it is checked at build time instead of trusted.
  bool involutionValid = false;
};

// Number of shuffle iterations needed to reach a given delta standard deviation, Equation 3.
// The dominant term is sigma^2/2; the negative powers are the paper's fit correction, which only matters for small sigma.
uint32_t CalculateReSTIRPTPairingShuffleCount(float sigma);

// Builds one pairing texture. `seed` decorrelates the several textures a frame uses from each other.
ReSTIRPTPairingTexture GenerateReSTIRPTPairingTexture(uint32_t size, float sigma, uint32_t seed);

}  // namespace rtpt
